server:
  forward-headers-strategy: framework
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
cors:
  allow-origins:
    - ${ALLOWED_ORIGIN_SERVER_URL}
frontend:
  auth-callback-url: ${FRONTEND_AUTH_CALLBACK_URL}
