-- 관리 서버 ID sequence
create sequence server_info_id_seq;
-- refresh_token ID sequence
create sequence refresh_token_id_seq;
-- app_push_token ID sequence
create sequence app_push_token_id_seq;
-- app_push_msg ID sequence
create sequence app_push_msg_seq;

-- 사용자 정보
create table user_info
(
    username    varchar(100) primary key,
    password    varchar(100) not null,
    name        varchar(10)  not null,
    created_at  timestamp    not null default current_timestamp,
    modified_at timestamp    not null default current_timestamp
);

-- 관리 서버 정보
create table server_info
(
    id               bigint primary key    default nextval('server_info_id_seq'),
    server_name      varchar(100) not null unique,
    activate         bool         not null default false,
    hosting_url      varchar(500),
    health_check_url varchar(500) not null,
    management_url   varchar(500) not null,
    user_id          varchar(100) not null,
    created_at       timestamp    not null default current_timestamp,
    modified_at      timestamp    not null default current_timestamp,
    foreign key (user_id) references user_info (username)
);

-- refresh-token 정보
create table refresh_token
(
    id          bigint primary key    default nextval('refresh_token_id_seq'),
    token       varchar(512) not null unique,
    user_id     varchar(100) not null,
    created_at  timestamp    not null default current_timestamp,
    modified_at timestamp    not null default current_timestamp,
    foreign key (user_id) references user_info (username)
);

-- app-push-token 정보
create table app_push_token
(
    id          bigint primary key    default nextval('app_push_token_id_seq'),
    token       varchar(300) not null unique,
    device      varchar(300) not null,
    user_id     varchar(100) not null,
    created_at  timestamp    not null default current_timestamp,
    modified_at timestamp    not null default current_timestamp,
    foreign key (user_id) references user_info (username)
);

-- app-push-msg 정보
create table app_push_msg
(
    id            bigint primary key    default nextval('app_push_msg_seq'),
    title         varchar(100) not null,
    body          varchar(500) not null,
    push_sent     bool         not null default false,
    push_received bool         not null default false,
    created_at    timestamp    not null default current_timestamp,
    modified_at   timestamp    not null default current_timestamp,
    token_id      bigint       not null,
    foreign key (token_id) references app_push_token (id)
);

-- spring batch

-- Autogenerated: do not edit this file
CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL PRIMARY KEY,
    VERSION         BIGINT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT    NOT NULL PRIMARY KEY,
    VERSION          BIGINT,
    JOB_INSTANCE_ID  BIGINT    NOT NULL,
    CREATE_TIME      TIMESTAMP NOT NULL,
    START_TIME       TIMESTAMP DEFAULT NULL,
    END_TIME         TIMESTAMP DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(2500),
    EXIT_MESSAGE     VARCHAR(2500),
    LAST_UPDATED     TIMESTAMP,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
        references BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT       NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500),
    IDENTIFYING      CHAR(1)      NOT NULL,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT       NOT NULL PRIMARY KEY,
    VERSION            BIGINT       NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   BIGINT       NOT NULL,
    CREATE_TIME        TIMESTAMP    NOT NULL,
    START_TIME         TIMESTAMP DEFAULT NULL,
    END_TIME           TIMESTAMP DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       BIGINT,
    READ_COUNT         BIGINT,
    FILTER_COUNT       BIGINT,
    WRITE_COUNT        BIGINT,
    READ_SKIP_COUNT    BIGINT,
    WRITE_SKIP_COUNT   BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT     BIGINT,
    EXIT_CODE          VARCHAR(2500),
    EXIT_MESSAGE       VARCHAR(2500),
    LAST_UPDATED       TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
        references BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
