services:
  postgres:
    image: 'postgres:17.5'
    environment:
      POSTGRES_DB: cloudtype
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager0
    ports:
      - "5432:5432"
  redis:
    image: 'redis:8.6-alpine'
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: default0
    ports:
      - "6379:6379"
